title: LightNap
description: LightNap (lightweight .NET Core/Angular/PrimeNG) is a full stack starter kit designed to provide a boost to Single Page Applications (SPA).
theme: just-the-docs

url: https://lightnap.sharplogic.com

aux_links:
  Repository: https://github.com/SharpLogic/LightNap

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: yellow