name: Build and test

env:
  DOTNET_VERSION: '8'
  NODE_VERSION: '22'

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and test the back-end
        run: |
          cd src
          dotnet restore
          dotnet test

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install front-end dependencies
        run: |
          cd src/lightnap-ng
          npm install

      - name: Run front-end tests
        run: |
          cd src/lightnap-ng
          npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build front-end app and deploy into back-end site
        run: |
          cd src/lightnap-ng
          npm run deploy

      - name: Publish back-end app
        run: |
          cd src
          dotnet publish --configuration Release --output ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: src/publish