name: Deploy to Azure App Service

on:
  workflow_run:
    workflows: "Build, Test, and Publish"
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Quit if RUN_BUILD_TEST_PUBLISH is not set to true
        if: vars.RUN_BUILD_TEST_PUBLISH != 'true'
        run: |
          echo "Repo variable RUN_BUILD_TEST_PUBLISH is not set to 'true' so this workflow is disabled. Exiting..."
          exit 0
    
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./build
